### ISSUE TITLE
Doesn't work on 10.10.2

### ISSUE THREAD

**Issue by horsetamer** [FranticRain/Xone-OSX#23]
Hey, I just installed your driver and attempted to plug in my controller. The batteries were not in it, and the light would not come one. I pressed the home button and the light began to blink which indicates there is power from the micro-USB to USB connection. Thanks for any help. Also I am unsure of how to uninstall this driver.

**Comment by FranticRain** [comment]
To uninstall the driver, all you have to do is go to /Library/Extensions and remove the file "Xone Driver.kext". But before you do, I'd like to see what the problem is. If you could, could you run `sudo kextutil -t "/Library/Extensions/Xone Driver.kext"`from your terminal so I can figure out what the problem is?

**Comment by horsetamer** [comment]
new-host:~ horsetamer$ sudo kextutil -t "/Library/Extensions/Xone Driver.kext"
new-host:~ horsetamer$ 

This is what I get from running that

**Comment by FranticRain** [comment]
Did you try plugging in the controller after you ran that? It should work. Make sure to run it again before you test. It'll unload do to inactivity.

**Comment by horsetamer** [comment]
It's the same issue, nothing happens

**Comment by FranticRain** [comment]
Is this a Microsoft Xbox One controller? Could you check the Product ID and Vendor ID of the controller under: Apple Menu -> About This Mac -> System Report -> Hardware -> USB. The device is likely called "Controller" under that list.

**Comment by horsetamer** [comment]
Yes it is a Microsoft Xbox One controller, it's this one:

http://www.bestbuy.com/site/microsoft-xbox-one-special-edition-midnight-forces-wireless-controller-camouflage/7307001.p?id=1219265949449&skuId=7307001

On my USB Device Tree the controller actually doesn't seem to show up, I'm pretty sure the micro-USB is making a connection since it will light up when I press the xbox button and there are no batteries in it. I'll go grab my other xbox controller and another micro-usb cable and check this out.

Thanks for all your help so far man!

**Comment by FranticRain** [comment]
I was afraid that those camo controllers would have different Product ID's. You can also check that number in Windows if you have that handy.

**Comment by horsetamer** [comment]
Same issue with the black controller and a different micro-USB, neither of the devices seem to show up in my USB Device Tree

**Comment by FranticRain** [comment]
Well thats interesting. Thats some core incompatibility with 10.10.2. If the OS can't even see it, then my kext definitely isn't going to. This seems like its out of my hands, and is Apple's fault. I guess you just have to report that OS X can't see your controllers to Apple and hope they fix it. Also consider uninstalling the driver `sudo rm -rf "/Library/Extensions/Xone Driver.kext"` and then checking the device tree again. This is such a weird bug.

**Comment by horsetamer** [comment]
Yeah this is kinda weird, thanks for all the help! I'll definitely let you know if I figure this out.

**Comment by geowar1** [comment]
That is more likely a charging cable not a full USB signal cable.

**Comment by horsetamer** [comment]
I didn't know something like that existed, I'll look around for a different cable

**Comment by horsetamer** [comment]
Wow, props to you geowar1, I tried a different cable and it completely worked this time.

**Comment by FranticRain** [comment]
Totally didn't know that they made charge-only cables. At least its solved now!
