### ISSUE TITLE
Controller unresponsive after machine sleep/wake

### ISSUE THREAD

**Issue by pizthewiz** [FranticRain/Xone-OSX#25]
While the device can be seen via _USB Prober.app_ or _System Information.app_, on machine wake the Home/Xbox button does not re-illuminate and the none of the controller's inputs seem active in the pref pane. An un/re-plug does the trick, but I wasn't sure if there was something else that could be done.

**Comment by FranticRain** [comment]
How long does the computer need to be asleep see this happen? I've been messing with it and the controller just stays on when I sleep my laptop.

**Comment by pizthewiz** [comment]
For me, it took perhaps 60 seconds for the Home/Xbox button to go out.

**Comment by FranticRain** [comment]
Try this pre-release. Don't know if it'll work or not. https://github.com/FranticRain/Xone-OSX/releases/tag/v0.4.2

**Comment by pizthewiz** [comment]
Sadly no dice, this is occurring on a `MacBookPro11,3` running 10.10.2 and occurs when plugged or not. I'll try it on an `iMac11,1` and see if I have better luck over there.

**Comment by pizthewiz** [comment]
The controller seems to stay powered up through sleep of my `iMac11,1`, though the machine seems to have power management issues so I'm not sure it is a great reference point.

**Comment by FranticRain** [comment]
I figured out I had NoSleep installed and thats why my controller wasn't going to sleep. So now I can finally test this and fix it. It seems I'm not getting the "kIOMessageDeviceSignaledWakeup" message. It's unwillingness to appear may be related to that renegade "kIOMessageServiceIsRequestingClose" that shows up when the driver starts. I'll keep working on it.

**Comment by FranticRain** [comment]
[Latest release candidate should fix this issue.](https://github.com/FranticRain/Xone-OSX/releases/tag/v1.0.0-rc) Let me know how it works.

**Comment by pizthewiz** [comment]
Whoa, that is a substantial commit - I'll give this a try soon.

**Comment by pizthewiz** [comment]
Yup this now works! The installers lost their signatures but this is good to go.

**Comment by FranticRain** [comment]
D'oh. Can't believe I forgot that. I re-uploaded the dmgs with signed pkgs. Should be fixed.
