### ISSUE TITLE
Sign binary installer package releases

### ISSUE THREAD

**Issue by pizthewiz** [FranticRain/Xone-OSX#26]
It looks like the the installer packages on the [Releases page](https://github.com/FranticRain/Xone-OSX/releases) are not signed:

```sh
$  pkgutil --check-signature ~/Downloads/Xone.Driver.Installer.pkg
Package "Xone.Driver.Installer.pkg":
   Status: no signature
```

As an aside, it would be awesome if the version were included in the filename, like _Xone-Driver-0.4.1.pkg_.

**Comment by FranticRain** [comment]
Updated them. Are they signed properly?

**Comment by pizthewiz** [comment]
Thanks! The packages now open without any complaints from Gatekeeper.
