### ISSUE TITLE
3rd Party Controller support

### ISSUE THREAD

**Issue by reedptaylor** [FranticRain/Xone-OSX#39]
Is there any way you can get this controller working? Its the PowerA Spectra Illuminated Controller for Xbox one.   Product ID:	0x542a
  Vendor ID:	0x24c6

**Comment by FranticRain** [comment]
I'm so so so so sorry for missing this issue for so long. [This version of the driver](https://github.com/FranticRain/Xone-OSX/releases/tag/v1.0.1) should work with your controller. Let me know if you have any more problems.

**Comment by reedptaylor** [comment]
Still no good:/ Controller just keeps blinking and the software doesn't see it

**Comment by FranticRain** [comment]
Can you make sure that your controller shows up in the USB section of System Report when it is plugged in with or without the driver?

**Comment by geowar1** [comment]
FranticRain: You should post an FAQ/troubleshooting guide; I'd guess about half the issues reports here are power-only USB cables. Most of the rest are "update to latest driver".

**Comment by reedptaylor** [comment]
Yeah it has shown up there since before I installed the driver!

**Comment by FranticRain** [comment]
So basically what this is telling me is that your cable is good and OS X recognizes the controller, but the driver isn't matching to it. This might be an outrageous question, but have you rebooted? As far as I understand, the controller should have matched without problem.

**Comment by reedptaylor** [comment]
Rebooted and reinstalled

**Comment by FranticRain** [comment]
Okay, let me compile a version with debug output enabled, and then we will see what the problem is.

**Comment by FranticRain** [comment]
Okay, install this version, and then look at Console.app to see output from the driver. https://www.dropbox.com/s/sox8m8ktdvn4iik/Xone-Driver-360-1.0.1.dmg?dl=0

**Comment by reedptaylor** [comment]
alright I'll let you know when I get home. Appreciate it!

**Comment by reedptaylor** [comment]
Let me know if this is what you need: https://www.dropbox.com/sh/m3k2056ahfzshfu/AADLIvdbLo5ejsCwVL-fNPh2a?dl=0

**Comment by FranticRain** [comment]
I need the "All Messages" section of Console.app located in Applications/Utilities. It looks roughly like this: https://www.dropbox.com/s/1nr4asmdngxcljw/Screenshot%202015-04-13%2023.04.37.png?dl=0

**Comment by reedptaylor** [comment]
Alright I updated the dropbox folder

**Comment by FranticRain** [comment]
Since I'm not even seeing anything from the driver in the log, the controller isn't even pairing with the driver.

There is some issue with PowerA controllers that my driver doesn't like. I'm not sure what it is.

@geowar1 Do you have any idea why the PowerA controllers would refuse to even get to ```start```?

**Comment by FranticRain** [comment]
Please uninstall my driver and try using this beta version of this driver instead: https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview7.pkg

I've been porting my code into it, and it definitely works with the Microsoft controller. Hopefully it also works with third party controllers.

**Comment by reedptaylor** [comment]
It works!!!!

**Comment by FranticRain** [comment]
Awesome! Fantastic. When the official version of that driver comes out, this one will be deprecated. In the future, please use [the 360Controller repsitory](https://github.com/d235j/360Controller) for all of your Xbox One controller needs. I'll be around there if you have any further problems.
