### ISSUE TITLE
Analog-Stick mapping

### ISSUE THREAD

**Issue by karstenBriksoft** [FranticRain/Xone-OSX#4]
Hi there,

i've tried the driver in the game Mercenary Kings and in the game is a Map-View where you can navigate the map using the right analog stick. Every time i open the map, it scrolls to the left and i need to use the left trigger to scroll to the right. My guess is that the Left trigger and the right analog stick's x-axis are mixed up.

Karsten

**Comment by s0nera** [comment]
Dudes! You are all awesome. I can't wait for it to work. Happy new year.

**Comment by FranticRain** [comment]
Here's what I have so far. The axes map properly for Race the Sun and Awesomenauts. Risk of Rain is a complete mess.
The only buttons it recognizes are:
LB as Left Stick Click
Left Stick Click as LB
Right Stick Click as RB
D-Pad Left as Start
D-Pad Right as Select
And on top of that, if you move the left stick, the mouse snaps to the top left corner.
I don't own RocketsRocketsRockets, so I can't test that. I've purchased a Play and Charge kit for an Xbox 360 controller to see how Risk of Rain interacts with it, as well as to check for certain how it all maps with Awesomenauts. I'm not sure I should release it yet, but it may take a little while for that cable to get shipped.

**Comment by s0nera** [comment]
I think the Xbox 360 controller need a wireless receiver to work. The play
and charge kit only do power the controller, or at least is that what
happens with mine.

My friend has this receiver and I used to play risk of rain with him using
my 360 controller. And that's the reason I look forward for this driver, so
I don't need to buy a receiver for myself.

In RocketsRocketsRockets the controller acts just as in risk of rain. In
settings there is possible to choose the "schematics" of the controller to
apply on the hardware one is using. I choose the 360 controller while using
the Xbox one's, nothing happened and now I can't change it back to not 360
controller. Uninstalling the game didn't make it too.

Thanks for helping.

**Comment by FranticRain** [comment]
I actually figured out that there is a more current, signed version of the Tattiebogle driver here on github that works with my wireless receiver. So I hooked it up and took a look at the bindings. What I'm seeing through Awesomenauts is that the button order is based on the packing of the packet sent from the controller. IE, the Xbox One controller sends the buttons in this order: Sync, Menu, View, A, B, X Y, etc. While the Xbox 360 controller sends them in the order Up, Down, Left, Right, Start, Back. It completely ignores my binding of the controls.

So I'm going to try and reorder the packet from within my driver, but if that doesn't work, it means that the Xbox One controller is going to be seriously crippled in the way of support. Games that have good controller mapping like Awesomenauts will work with some quick remapping, but ones with garbage support like Risk of Rain may not work.

**Comment by FranticRain** [comment]
The good news is that the bit swapping worked perfectly for Awesomenauts. The bad news is that it doesn't want to play nice with Risk of Rain. I'll keep looking into it.

**Comment by FranticRain** [comment]
Try this new version. It won't work with Risk of Rain, but I've asked the developers for a bit of information to try and figure it out.

**Comment by s0nera** [comment]
Thank you. You are awesome.

**Comment by karstenBriksoft** [comment]
i've just found time to try with the games that i had problems with and the new version makes the controller behave like the old 360 controller. Thanks a lot! Awesome work!
