### ISSUE TITLE
v1.0.0 not Working

### ISSUE THREAD

**Issue by sexto** [FranticRain/Xone-OSX#42]
With the last Alpha, all games I tried worked perfectly, but with the latest release, even the controller appears in The Xone Controller Menu under System Preferences and works when I push all the buttons, none works. I tried Tomb Raider, VVVVVV and Don't Starve Together. All the Steam version.

**Comment by FranticRain** [comment]
Are you using the Xone-Driver-1.0.0-rc.dmg or the Xone-Driver-360-1.0.0-rc.dmg install of the driver?

**Comment by sexto** [comment]
Xone-Driver-1.0.0 (not rc).

Thanks for the fast feedback.

**Comment by FranticRain** [comment]
Use the -360 version. The non-360 version is for people who want the raw mapping of the Xbox One controller. It will not work with most games, but people asked for it, so its there. The -360 version works with most games that support the Xbox 360 Controller.

**Comment by sexto** [comment]
Yes. It works!

Thank you. Good job.
