### ISSUE TITLE
Only old version of the driver works with Dirt 2

### ISSUE THREAD

**Issue by RougeTomate** [FranticRain/Xone-OSX#45]
Hello and thanks for the driver. I am using version 0.4.0 right now on my rMBP (latest Yosemite) and everything works just fine. However, when I updated to v.1.0.0 and v.1.0.0-rc, the controller was active in the preference pane, but was not recognized by the game. Any reason why?

**Comment by FranticRain** [comment]
Use the -360 version of the driver for games. Most likely you downloaded ```Xone-Driver-1.0.0.dmg``` meaning that you didn't read the release text. You need ```Xone-Driver-360-1.0.0.dmg``` for games.
