### ISSUE TITLE
System preferences crashes when I hit Xone icon 

### ISSUE THREAD

**Issue by nicktothek** [FranticRain/Xone-OSX#49]
not only that the controller will not turn on when connected, it shows up in the system report and all but will not work!! please help

**Comment by FranticRain** [comment]
Please follow the troubleshooting guidelines and then let me know what happens: https://github.com/FranticRain/Xone-OSX#troubleshooting

**Comment by nicktothek** [comment]
It shows up in system report, but it doesn't light up when I plug it in. Also like I said in the title I click the Xone icon on the system preference page and it crashes and says "system preferences has quit unexpectingly"

**Comment by FranticRain** [comment]
Are your product and vendor IDs the same as the example?

**Comment by nicktothek** [comment]
Yeah

**Comment by FranticRain** [comment]
What version of OSX and what version of the driver are you using?

**Comment by nicktothek** [comment]
Im running 10.8.5 and I'm using Xone 4.0

**Comment by FranticRain** [comment]
This driver is not officially supported on version of OS X earlier than 10.9. If you want to try and run it on 10.8.5, copy "Xone Driver.kext" from /Library/Extensions to /System/Library/Extensions.

**Comment by nicktothek** [comment]
what driver is supported on 10.8.5?

**Comment by FranticRain** [comment]
This one may: https://github.com/guilhermearaujo/xboxonecontrollerenabler

**Comment by nicktothek** [comment]
I can only find the version supported by 10.9

**Comment by FranticRain** [comment]
Since OS X driver stuff changed with 10.9, and the Xbox One controller was released after 10.9. So no one wants to support it.
