### ISSUE TITLE
Team Fortress 2?

### ISSUE THREAD

**Issue by asianblackman** [FranticRain/Xone-OSX#50]
I understand that you have a busy life but I would be so grateful if you make the driver compatible with tf2, first shooter games, and more steam games like Left For Dead, etc.

**Comment by FranticRain** [comment]
Are you using the "Xone-Driver-360-1.0.1.dmg" version of the driver?

**Comment by asianblackman** [comment]
I'm using an xbox one controller and using the Xone one version

**Comment by FranticRain** [comment]
You want the 360 version. The release page states in bold "FOR BEST SUPPORT WITH GAMES USE: Xone-Driver-360-1.0.1.dmg" That will make source games work.
