### ISSUE TITLE
product and vendor ID 

### ISSUE THREAD

**Issue by trdavi2** [FranticRain/Xone-OSX#51]
Product ID:	0x542a
  Vendor ID:	0x24c6

**Comment by FranticRain** [comment]
What is the name of this device, for my records.

**Comment by FranticRain** [comment]
Oh. Its a PowerA Spectra Illuminated controller. Do you know you to use a USB packet sniffer in windows?

**Comment by trdavi2** [comment]
No and I'm on a mac.

Quoting Drew Mills <notifications@github.com>:

> Oh. Its a PowerA Spectra Illuminated controller. Do you know you to  
> use a USB packet sniffer in windows?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/FranticRain/Xone-OSX/issues/51#issuecomment-99630454



----------------------------------------------------------------
This message was sent using Illinois State University RedbirdMail

**Comment by FranticRain** [comment]
That controller is already supported in code. However, it does not follow the standards for starting an Xbox One controller. It does not work with this driver until someone with a Windows machine can test it with a packet sniffer.

**Comment by FranticRain** [comment]
Please uninstall my driver and try using this beta version of this driver instead: https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview7.pkg

I've been porting my code into it, and it definitely works with the Microsoft controller. Hopefully it also works with third party controllers.
