### ISSUE TITLE
Xbox One mini?

### ISSUE THREAD

**Issue by patathom** [FranticRain/Xone-OSX#54]
I bought a Xbox One mini controller. It's on the list but it isn't detected in the program. Any solution?

P.S I'm running it on Yosemite 10.10.3.Thank you
Thank you

**Comment by FranticRain** [comment]
I haven't gotten 3rd party controller support down quite just yet. So try this experimental version of the driver and let me know if it works.

https://dl.dropboxusercontent.com/u/33409904/Xone-Driver-1.0.2-r3.dmg

Also make sure to follow the troubleshooting instructions and make sure that your controller is showing up as connected, and you don't have a bad cable.

**Comment by patathom** [comment]
First, thank you very much for answering this quick.

The other program is suppose to change the previous in the settings or to install a new one?
Because it isn't working.
For the troubleshooting, my controller is in the menu, but it is not detected in the program.

**Comment by FranticRain** [comment]
The installer should have overwritten the first driver with a new one. What you are really looking to see is whether or not your controller lights up. Does your controller light up at all?

**Comment by patathom** [comment]
Nope, not at all

**Comment by patathom** [comment]
do I need to uninstall the first?

**Comment by FranticRain** [comment]
No. The new installer will overwrite the first one. Try this other one. Maybe it will yield different results. https://dl.dropboxusercontent.com/u/33409904/Xone-Driver-1.0.2-r4.dmg

If It doesn't work, Look in Console.app located in Applications/Utilities. Let me know if you see anything in there that looks like: "Xbox One Controller - handleStart"

**Comment by patathom** [comment]
When i finished installing the program, it's written that it cannot localize the necessary data. In the consol, there's a lot of "unmount initiated on xBox One Driver of /Volume/Xbox One Driver for OS X 1". My cable is good, it work on my Xbox One.

**Comment by FranticRain** [comment]
You need to look at the console directly after plugging the controller in. I need to know what's happening when the controller is plugged in.

**Comment by patathom** [comment]
"Spindump: invalid connection: com.apple.coresymbolicationd" and "com.apple.xpc.lunchd"

"The_DirtyJetsamMermoryLimit key is not available on this platform"

**Comment by FranticRain** [comment]
The driver isn't even seeing the controller. Can you just make sure that your Vendor ID is 0x24C6 and your Product ID is 0x541A ?

**Comment by patathom** [comment]
Yes it's that

**Comment by FranticRain** [comment]
Okay, try this out and let me know what score you get in Console.app.
https://dl.dropboxusercontent.com/u/33409904/Xone-Driver-1.0.3-r1.dmg
The format should be "Score - XXXXX". For example, mine is "Score - 90000"

**Comment by Badbubba** [comment]
Hi, i am experiencing same problem as patathom describes. Using Xbox one mini Vendor ID 0x24c6 and product id is 0x541A, Mac running Yosemite 10.10.03. Any progress on solving this issue ?

**Comment by FranticRain** [comment]
There is no new progress. I'm not sure what the problem is, I'm working on something that might fix it though.

**Comment by FranticRain** [comment]
Please uninstall my driver and try using this beta version of this driver instead: https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview7.pkg

I've been porting my code into it, and it definitely works with the Microsoft controller. Hopefully it also works with third party controllers.

**Comment by patathom** [comment]
I couldn't find the "uninstall.command" if I re-download the original program, will it be there?

**Comment by FranticRain** [comment]
Yes. The uninstaller is included in all of the latest versions and will uninstall any version of the driver.

**Comment by patathom** [comment]
It worked thank you so much for all the help!!

**Comment by FranticRain** [comment]
Awesome! Fantastic. When the official version of that driver comes out, this one will be deprecated. In the future, please use the 360Controller repsitory for all of your Xbox One controller needs. I'll be around there if you have any further problems.
