### ISSUE TITLE
1.0.3 installer ships 1.0 version

### ISSUE THREAD

**Issue by mrbohnke** [FranticRain/Xone-OSX#60]
Maybe it's only me, but I installed 1.0.3, using the installer, four times now (three of them uninstalling first) and I always get 1.0 version of the stuff.
Thanks for your time!

**Comment by FranticRain** [comment]
Its 1.0.3. Since the X.X.3 is just a build number, I don't bother to update the number on the kext. You have the latest version.

**Comment by mrbohnke** [comment]
Oh ah. Silly me. Thank you very much then!
