### ISSUE TITLE
Support for Power-A Mini Controllers

### ISSUE THREAD

**Issue by tylerrrobertson** [FranticRain/Xone-OSX#62]
Product ID: 0x541a
Vendor ID: 0x24c6

**Comment by FranticRain** [comment]
There is a big bold line on the releases page that says: "IF YOU ARE USING A THIRD PARTY CONTROLLER [USE THE DRIVER AT THIS LINK.](https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview7.pkg)." Please uninstall my driver and install the other one instead. It works with the Power-A Mini controller. An uninstaller is included in your original install .dmg. If you no longer have that .dmg, you can download the latest version of the driver and it will contain the uninstaller.
