### ISSUE TITLE
Not compatible with El Capitan

### ISSUE THREAD

**Issue by blindpilot17** [FranticRain/Xone-OSX#67]
Hey I know it hasn't been released yet but just to make aware that this driver isn't working on the next operating system for Mac.

**Comment by FranticRain** [comment]
Could you uninstall my driver and try out this driver: https://dl.dropboxusercontent.com/u/14890209/Install360Controller0.15Preview7.pkg

Once they finally put out an official release, this driver will be deprecated. Hopefully that will happen before El Capitan releases. I haven't read any news about kext changes in El Capitan. Will have to look into that.

**Comment by blindpilot17** [comment]
it works!! Thanks a ton!!

**Comment by FranticRain** [comment]
Awesome. Hopefully everything works out and then I will deprecate this driver at the proper time.
