### ISSUE TITLE
Xone-OSX conflicts with d235j/360controller in some programs

### ISSUE THREAD

**Issue by blakekl** [FranticRain/Xone-OSX#69]
i use the d235j/360Controller driver for my 360 controllers and I'm trying to get this controller to work with it. Problem is that sometimes I use ControllerMate to add joystick support to games that don't support it natively. It see's these two devices as the same, but their button layouts are completely different. This makes working with both impossible in my situation. The devices appear to be different in my system profiler, but the same in controllermate. Interestingly, controllmate see's the device as a different device when I use the 'OLDBIND' version, but the buttons are just wonky in that case.

Below are screenshots of the system profiler for both a 360 and xone controller. Also, the bindings shown for 360 controller in ControllerMate. I'll add the xone bindings in controllerate after installing that driver again.

System Profile of 360 Controller
![screen shot 2015-08-02 at 2 47 29 pm](https://cloud.githubusercontent.com/assets/1930170/9027952/a481727c-3925-11e5-9760-6610683117b3.png)

System Profile of XOne Controller
![screen shot 2015-08-02 at 2 47 33 pm](https://cloud.githubusercontent.com/assets/1930170/9027953/a4845690-3925-11e5-8751-d64735647b93.png)

Controllermate Bindings of 360 Controller
![screen shot 2015-08-02 at 2 48 22 pm](https://cloud.githubusercontent.com/assets/1930170/9027951/a47b997e-3925-11e5-8cdc-b637dece5df4.png)

Controllermate Bindings of XOne (OLDBINDINGS version)
![screen shot 2015-08-02 at 3 01 44 pm](https://cloud.githubusercontent.com/assets/1930170/9028041/99aabee6-3928-11e5-9b69-ea1934ca9617.png)

Controllermate Bindings of 360 and normal XOne version (XOne input on left, perceived 360 output on right)
A = RStick Button
B = LB
X = RB
Y = Guide Button
LB = Start
RB = Back
Menu = DPad Up
View = DPad Down 
Guide = Nothing?
DPad Up = Nothing?
DPad Down = Nothing?
DPad Right = Byte Count?
DPad Left = Nothing?
All Sticks = A
LT = A + Y
RT = A

So pushing Y on my XOne button registers as the guide button on a 360 controller in controller mate.
This means I'm unable to use a 360 controller and an xbox one controller at the same time because the bindings are so off. Not sure what the issue is here, but does it have something to with the changes to make older games that have built in support for the 360 controller work correctly?

**Comment by FranticRain** [comment]
The latest version of the d235j/360controller driver includes Xbox One controller support that I added. Just uninstall my driver, and update 360Controller, that will most likely solve most of your problems.

**Comment by blakekl** [comment]
Alright, will give that a try.

**Comment by blakekl** [comment]
Excellent. That solves my problem perfectly. Thanks for the quick response too. Greatly appreciated.
