### ISSUE TITLE
Newer xbox one controller not working. 

### ISSUE THREAD

**Issue by Turtlecat33** [FranticRain/Xone-OSX#71]
I have a good cord and a newer controller, (it has the extra headphone jack on the bottom) but when I try to connect it it doesnt pick up the controller. Help pls

**Comment by mattwagstaff** [comment]
Same issue here I think... .looks like it's on the cards to fix.
#63

**Comment by FranticRain** [comment]
That controller will not work, and will never work with this driver. However, it will work with the [360Controller repository](https://github.com/d235j/360Controller/) as soon as [they accept my pull request.](https://github.com/d235j/360Controller/pull/120)

**Comment by Turtlecat33** [comment]
Okay! Im using OpenEmu to play emulators on my macbook pro. Any recommendations on a controller to get for it?

**Comment by geowar1** [comment]
PS3 & PS4 controllers will work “out of the box”.

> On Aug 18, 2015, at 10:13 PM, Turtlecat33 <notifications@github.com> wrote:
> 
> Okay! Im using OpenEmu to play emulators on my macbook pro. Any recommendations on a controller to get for it?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/FranticRain/Xone-OSX/issues/71#issuecomment-132449463>.
> 

-- 
Enjoy,
George Warner, 
eMail/iChat: <geowar1@mac.com>

**Comment by FranticRain** [comment]
This driver will be deprecated when there is a full release of the 360Controller driver, so feel free to use the Xbox One controller. It works really well. OpenEmu uses a really great controller library called DDHidLib. It will work with pretty much all controllers. Even stuff like usb SNES controllers, if you're into that kind of thing.
