### ISSUE TITLE
button map scrambled and random button presses in Nuclear Throne

### ISSUE THREAD

**Issue by Fire-** [FranticRain/Xone-OSX#73]
http://store.steampowered.com/app/242680

The controller is recognized but the key mappings are off. The Y button acts as A or X, the B button is being pressed constantly for no apparent reason. It's just very strange.

**Comment by FranticRain** [comment]
Uninstall my driver and [try this driver instead.](https://github.com/d235j/360Controller/releases) A lot of games don't like my driver, but will work perfectly well with that driver, which I ported my code into.
