### ISSUE TITLE
Horipad one does not work on mac...

### ISSUE THREAD

**Issue by creativexp** [FranticRain/Xone-OSX#75]
Just bought a officially licensed microsoft xbox one controller made by Hori. Installed v1.0.4 of your driver and it does not recognise the controller on Mac. It is being recognised by system report but not in the xbox system preference menu.

I tried the 360Controller 0.15 (beta 3) driver released by @RodrigoCard and that didn't work.

I tried the link to a driver on dropbox as well with no luck.

**Comment by FranticRain** [comment]
Third party controller do not work with this repository. Further communications will occur on the 360Controller repository.
