### ISSUE TITLE
New product ID

### ISSUE THREAD

**Issue by purpleswag117** [FranticRain/Xone-OSX#77]
Sorry if you read this before I added text, I hit return before the post was ready. 

Anyway, on to what this post is about:

I have an official Microsoft Xbox One controller that has spotty driver support. The controller is recognized in system info, it's detected on the preferences pane, but no input is detected and the Xbox button does not illuminate. It has a different device and vendor ID than the one in the screenshot on the info page.

The product and vendor ID is:

  Product ID:	0x02dd
  Vendor ID:	0x045e  (Microsoft Corporation)

I may edit the kext myself but you did say to post an issue.

**Comment by FranticRain** [comment]
Ah. Thats the 3.5mm jack 2015 controller. Unfortunately that controller doesn't work with this driver. Really, this driver only works with the original MS controller. It's kind of a joke at this point. This driver is effectively deprecated now. I've been pushing my code into a driver that has much better support. If you uninstall my driver and [install this one instead](https://github.com/360Controller/360Controller/releases) it'll work perfectly. I'm just waiting for them to put out an official release, and then this driver will be fully deprecated.
