### ISSUE TITLE
Product ID not Recognized

### ISSUE THREAD

**Issue by Poison58** [FranticRain/Xone-OSX#78]
Hi, i plugged my Xbox One controller and the light doesn't turn on.

I check the controller's product and Vendor ID and the product ID doesn't match.

Product ID of my Controller:  0x02dd

**Comment by FranticRain** [comment]
This driver is deprecated. Please use [this driver](https://github.com/360Controller/360Controller/releases) instead.
Unfortunately, this driver only works with the original Xbox One controller for some reason, so I've moved all of my code to a more robust driver that supports later Xbox One controllers in addition to 3rd party controllers.

**Comment by Poison58** [comment]
thanks, now it works perfect


2015-10-19 20:24 GMT+02:00 Drew Mills <notifications@github.com>:
