### ISSUE TITLE
XBOX One Elite Controller

### ISSUE THREAD

**Issue by kventil** [FranticRain/Xone-OSX#79]
Hi,

the Elite Controller does not seem to work.

  Product ID:	0x02e3
  Vendor ID:	0x045e  (Microsoft Corporation)
  Version:	2.03

Do you need any additional Infos? :)

Cheers
Robert

**Comment by FranticRain** [comment]
This driver is deprecated. Please use [this driver](https://github.com/360Controller/360Controller/releases) instead.
Unfortunately, this driver only works with the original Xbox One controller for some reason, so I've moved all of my code to a more robust driver that supports later Xbox One controllers in addition to 3rd party controllers.

I'll submit a pull request there to get it added, but the managers of the repository are notoriously slow to accept pull requests, sorry.
