### ISSUE TITLE
Controller does not have reliable response

### ISSUE THREAD

**Issue by vinft10** [FranticRain/Xone-OSX#80]
When i press the A button and look at the application, it shows the a button either not light up at all, stay lit up even when i have let go of the button, or react normally and turn on and off. This only seems to happen with the ABXY and start select buttons on the Xbox one controller.

**Comment by FranticRain** [comment]
This driver is deprecated. Please use [this driver](https://github.com/360Controller/360Controller/releases) instead.
Unfortunately, this driver only works with the original Xbox One controller for some reason, so I've moved all of my code to a more robust driver that supports later Xbox One controllers in addition to 3rd party controllers.
