### ISSUE TITLE
Different Product ID

### ISSUE THREAD

**Issue by estaoscuroaqui** [FranticRain/Xone-OSX#85]
Hi, 

I have an official Microsoft Xbox One controller. I plugged it and the light doesn't turn on.
The Product ID does not match. The vendor ID it's ok.

Here's the product ID of my controller: 0x028e

Thanks in advance!

**Comment by FranticRain** [comment]
This driver is deprecated. Please use [this driver](https://github.com/360Controller/360Controller/releases) instead.
Unfortunately, this driver only works with the original Xbox One controller for some reason, so I've moved all of my code to a more robust driver that supports later Xbox One controllers in addition to 3rd party controllers.

**Comment by estaoscuroaqui** [comment]
Thanks!
