### ISSUE TITLE
Xbox One controller now working with steam using 0.15 beta

### ISSUE THREAD

**Issue by skenj** [FranticRain/Xone-OSX#86]
Hi,

Just trying to get my xbox one controller to work with steam and counterstrike and not having much luck. i have installed the driver (0.15 beta) and it tests ok within OS X and it is also seen in steam shell however it is not seen in counterstrike. Would this be a counterstrike port issue?

**Comment by FranticRain** [comment]
If you are having issues with the 360Controller repository, post your issues there. This is not an issue with the driver, this is a game level issue. You can find this out simply by googling, or checking old issues on the 360Controller repository. These links might help you: https://imgur.com/a/a7zRs and https://steamcommunity.com/app/730/discussions/0/540744934368026446/
