### ISSUE TITLE
The controller and the software show up on my Mac, but the controller won't turn on

### ISSUE THREAD

**Issue by The-Meme-Lord** [FranticRain/Xone-OSX#87]
And the software recognizes that there is a controller, but it just won't turn on.

**Comment by The-Meme-Lord** [comment]
And the software recognizes that there is a controller, but it just won't turn on.

**Comment by FranticRain** [comment]
This driver is deprecated. Please use [this driver](https://github.com/360Controller/360Controller/releases) instead.
Unfortunately, this driver only works with the original Xbox One controller for some reason, so I've moved all of my code to a more robust driver that supports later Xbox One controllers in addition to 3rd party controllers.
