### ISSUE TITLE
Xbox one controller won't connect to my xbox one

### ISSUE THREAD

**Issue by ImaginAsian** [FranticRain/Xone-OSX#88]
So the xbox one controller is working in my mac but now i want to connect it back to my xbox one..... but it won't let me connect the controller to it. Ive un-installed xone and tried connecting the controller again nothing happened. PLSS HELP

**Comment by FranticRain** [comment]
The first step is to unplug the controller from you Mac.
Step two is to use the abundant Microsoft documentation to solve your problem: https://support.xbox.com/en-US/xbox-one/accessories/connect-a-wireless-controller
