### ISSUE TITLE
Controller is showing up in the usb but wont connect

### ISSUE THREAD

**Issue by Wingzero007** [FranticRain/Xone-OSX#89]
I tried to connect it to my laptop as usual but it wont work i think it has to do with my controller version its 2.03 can I any help with this?

**Comment by FranticRain** [comment]
This driver is deprecated. Please use [this driver](https://github.com/360Controller/360Controller/releases) instead.

Make sure to use the `uninstall.command` included in the .dmg file for this driver to uninstall Xone-OSX
